
CREATE EXTERNAL TABLE ext.NATION (
	N_NATIONKEY		INT				NOT NULL,
	N_NAME			CHAR(25)		NOT NULL,
	N_REGIONKEY		INT				NOT NULL,
	N_COMMENT		VARCHAR(152)	NULL
	)
WITH (
    LOCATION = 'nation/',
    DATA_SOURCE = eds_tpch, 
    FILE_FORMAT = ff_pipeDelimited
);
GO

CREATE EXTERNAL TABLE ext.REGION (
	R_REGIONKEY		INT				NOT NULL,
	R_NAME			CHAR(25)		NOT NULL,
	R_COMMENT		VARCHAR(152)	NULL

	)
WITH (
    LOCATION = 'region/',
    DATA_SOURCE = eds_tpch, 
    FILE_FORMAT = ff_pipeDelimited
);
GO

CREATE EXTERNAL TABLE ext.PART (
	P_PARTKEY		INT				NOT NULL,
	P_NAME			VARCHAR(55)		NOT NULL,
	P_MFGR			CHAR(25)		NOT NULL,
	P_BRAND			CHAR(10)		NOT NULL,
	P_TYPE			VARCHAR(25)		NOT NULL,
	P_SIZE			INT				NOT NULL,
	P_CONTAINER		CHAR(10)		NOT NULL,
	P_RETAILPRICE	DECIMAL(15,2)	NOT NULL,
	P_COMMENT		VARCHAR(23)		NOT NULL
	)
WITH (
    LOCATION = 'part/',
    DATA_SOURCE = eds_tpch, 
    FILE_FORMAT = ff_pipeDelimited
);
GO

CREATE EXTERNAL TABLE ext.SUPPLIER (
	S_SUPPKEY     INT				NOT NULL,
	S_NAME        CHAR(25)			NOT NULL,
	S_ADDRESS     VARCHAR(40)		NOT NULL,
	S_NATIONKEY   INT				NOT NULL,
	S_PHONE       CHAR(15)			NOT NULL,
	S_ACCTBAL     DECIMAL(15,2)		NOT NULL,
	S_COMMENT     VARCHAR(101)		NOT NULL
	)
WITH (
    LOCATION = 'supplier/',
    DATA_SOURCE = eds_tpch, 
    FILE_FORMAT = ff_pipeDelimited
);
GO

CREATE EXTERNAL TABLE ext.PARTSUPP (
	PS_PARTKEY     INT				NOT NULL,
	PS_SUPPKEY     INT				NOT NULL,
	PS_AVAILQTY    INT				NOT NULL,
	PS_SUPPLYCOST  DECIMAL(15,2)	NOT NULL,
	PS_COMMENT     VARCHAR(199)		NOT NULL
	)
WITH (
    LOCATION = 'partsupp/',
    DATA_SOURCE = eds_tpch, 
    FILE_FORMAT = ff_pipeDelimited
);
GO

CREATE EXTERNAL TABLE ext.CUSTOMER (
	C_CUSTKEY     INT				NOT NULL,
	C_NAME        VARCHAR(25)		NOT NULL,
	C_ADDRESS     VARCHAR(40)		NOT NULL,
	C_NATIONKEY   INTEGER			NOT NULL,
	C_PHONE       CHAR(15)			NOT NULL,
	C_ACCTBAL     DECIMAL(15,2)		NOT NULL,
	C_MKTSEGMENT  CHAR(10)			NOT NULL,
	C_COMMENT     VARCHAR(117)		NOT NULL
	)
WITH (
    LOCATION = 'customer/',
    DATA_SOURCE = eds_tpch, 
    FILE_FORMAT = ff_pipeDelimited
);
GO

CREATE EXTERNAL TABLE ext.ORDERS (
	O_ORDERKEY       INT			NOT NULL,
	O_CUSTKEY        INT			NOT NULL,
	O_ORDERSTATUS    CHAR(1)		NOT NULL,
	O_TOTALPRICE     DECIMAL(15,2)	NOT NULL,
	O_ORDERDATE      DATE			NOT NULL,
	O_ORDERPRIORITY  CHAR(15)		NOT NULL,  
	O_CLERK          CHAR(15)		NOT NULL, 
	O_SHIPPRIORITY   INT			NOT NULL,
	O_COMMENT        VARCHAR(79)	NOT NULL
	)
WITH (
    LOCATION = 'orders/',
    DATA_SOURCE = eds_tpch, 
    FILE_FORMAT = ff_pipeDelimited
);
GO

CREATE EXTERNAL TABLE ext.LINEITEM (
	L_ORDERKEY		INT				NOT NULL,
	L_PARTKEY		INT				NOT NULL,
	L_SUPPKEY		INT				NOT NULL,
	L_LINENUMBER	INT				NOT NULL,
	L_QUANTITY		DECIMAL(15,2)	NOT NULL,
	L_EXTENDEDPRICE DECIMAL(15,2)	NOT NULL,
	L_DISCOUNT		DECIMAL(15,2)	NOT NULL,
	L_TAX			DECIMAL(15,2)	NOT NULL,
	L_RETURNFLAG	CHAR(1)			NOT NULL,
	L_LINESTATUS	CHAR(1)			NOT NULL,
	L_SHIPDATE		DATE			NOT NULL,
	L_COMMITDATE	DATE			NOT NULL,
	L_RECEIPTDATE	DATE			NOT NULL,
	L_SHIPINSTRUCT	CHAR(25)		NOT NULL,
	L_SHIPMODE		CHAR(10)		NOT NULL,
	L_COMMENT		VARCHAR(44)		NOT NULL
	)
WITH (
    LOCATION = 'lineitem/',
    DATA_SOURCE = eds_tpch, 
    FILE_FORMAT = ff_pipeDelimited
);
GO

